#!/usr/bin/env bash
#
# Generates a .env with consistent secrets.
#
#   ./scripts/gen-env.sh zoia.example.com sfu.example.com > .env
#
# The LiveKit credentials appear in three places that must agree: the app reads
# LIVEKIT_API_KEY and LIVEKIT_API_SECRET, and the livekit container reads
# LIVEKIT_KEYS, which is those same two values as "key: secret". Getting them
# out of step produces an authentication failure at connect time with no useful
# error, so they are generated together here rather than by hand.

set -euo pipefail

APP_HOST="${1:-}"
SFU_HOST="${2:-}"

if [[ -z "$APP_HOST" || -z "$SFU_HOST" ]]; then
  echo "usage: $0 <app-hostname> <sfu-hostname>" >&2
  echo "   eg: $0 zoia.nullptrlabs.com sfu.nullptrlabs.com" >&2
  exit 1
fi

api_key="API$(openssl rand -hex 6)"
api_secret="$(openssl rand -base64 36 | tr -d '\n/+=' | head -c 44)"
session_secret="$(openssl rand -base64 48 | tr -d '\n')"

cat <<EOF
# Generated by scripts/gen-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Keep this file on the server only. It is excluded from git and from deploys.

PUBLIC_HOST=${APP_HOST}
SFU_HOST=${SFU_HOST}
LIVEKIT_WS_URL=wss://${SFU_HOST}

# Cloudflare API token scoped to Zone:DNS:Edit on this zone, for the ACME
# DNS-01 challenge. Fill this in by hand — it is not generated.
CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN:-PASTE_YOUR_TOKEN_HERE}
ACME_EMAIL=${ACME_EMAIL:-}

LIVEKIT_API_KEY=${api_key}
LIVEKIT_API_SECRET=${api_secret}
# Same pair, in the format the livekit container expects.
LIVEKIT_KEYS="${api_key}: ${api_secret}"

SESSION_SECRET=${session_secret}

ROOM_NAME=zoia
PORT=3000
# One proxy hop: the caddy container in front of the app.
TRUST_PROXY=1
SECURE_COOKIES=true
EOF
